"use server";

// Fal.ai API configuration for photogrammetry/3D mesh generation
const FAL_IMAGE_TO_3D_URL = "https://fal.run/fal-ai/triposr";
const FAL_FACE_TO_3D_URL = "https://fal.run/fal-ai/instant-mesh";

const FAL_FETCH_TIMEOUT_MS = 120_000;

function getFalKey(): string | null {
  const k = process.env.FAL_KEY;
  return k && k.trim().length > 0 ? k : null;
}

interface Fal3DResponse {
  model_url: string;
  model_mesh?: string;
  model_texture?: string;
  preview_url?: string;
  has_nsfw_concepts?: boolean[];
}

interface FalError {
  error: {
    message: string;
    type: string;
  };
}

interface GenerateMeshResult {
  success: boolean;
  meshUrl?: string;
  error?: string;
}

/**
 * Generates a 3D mesh from face photo using Fal.ai photogrammetry
 * @param formData - FormData containing the face photo
 * @returns Promise<GenerateMeshResult> - Result with mesh URL or error
 */
export async function generateFaceMesh(formData: FormData): Promise<GenerateMeshResult> {
  try {
    const falKey = getFalKey();
    if (!falKey) {
      return { success: false, error: "FAL_KEY not configured — photo upload still works without 3D mesh." };
    }

    console.log("[Server Action] Starting Fal.ai 3D mesh generation");

    // Extract the uploaded file from FormData
    const file = formData.get("face_photo") as File;
    if (!file) {
      return {
        success: false,
        error: "No face photo provided"
      };
    }

    console.log("[Server Action] Processing file:", file.name, file.size, "bytes");

    // Convert file to base64 Data URL for Fal.ai API
    const arrayBuffer = await file.arrayBuffer();
    const base64 = Buffer.from(arrayBuffer).toString('base64');
    const mimeType = file.type || 'image/jpeg';
    const dataUrl = `data:${mimeType};base64,${base64}`;

    // Prepare the request payload for Fal.ai 3D generation
    const payload = {
      image_url: dataUrl,
      // TripoSR specific parameters for high-quality 3D mesh generation
      foreground_ratio: 0.85,
      texture_resolution: 1024,
      remesh: true,
      vertex_count: -1, // Auto-optimize vertex count
    };

    console.log("[Server Action] Calling Fal.ai TripoSR API for 3D mesh generation...");

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), FAL_FETCH_TIMEOUT_MS);

    // Make the secure API call to Fal.ai TripoSR (Image-to-3D)
    let response: Response;
    try {
      response = await fetch(FAL_IMAGE_TO_3D_URL, {
        method: "POST",
        signal: controller.signal,
        headers: {
          "Authorization": `Key ${falKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });
    } finally {
      clearTimeout(timeoutId);
    }

    if (!response.ok) {
      const errorData = (await response.json()) as FalError;
      console.error("[Server Action] Fal.ai 3D API error:", response.status, errorData);
      
      return {
        success: false,
        error: `3D generation failed: ${errorData.error?.message || response.statusText}`
      };
    }

    const result = (await response.json()) as Fal3DResponse;
    console.log("[Server Action] Fal.ai 3D response:", {
      modelUrl: result.model_url ? "Present" : "Missing",
      previewUrl: result.preview_url ? "Present" : "Missing",
      hasNsfw: result.has_nsfw_concepts,
    });

    // Check for NSFW content
    if (result.has_nsfw_concepts?.some(Boolean)) {
      return {
        success: false,
        error: "Image contains inappropriate content and cannot be processed"
      };
    }

    // Extract the generated 3D model URL
    if (!result.model_url) {
      return {
        success: false,
        error: "No 3D mesh generated by Fal.ai"
      };
    }

    console.log("[Server Action] 3D mesh generated successfully:", result.model_url);

    return {
      success: true,
      meshUrl: result.model_url
    };

  } catch (error) {
    console.error("[Server Action] 3D mesh generation failed:", error);
    const msg =
      error instanceof Error
        ? error.name === "AbortError"
          ? `3D request timed out after ${FAL_FETCH_TIMEOUT_MS / 1000}s`
          : error.message
        : "Unknown error occurred";

    return {
      success: false,
      error: msg,
    };
  }
}

/**
 * Alternative function using InstantMesh for faster 3D generation
 * @param formData - FormData containing the face photo
 * @returns Promise<GenerateMeshResult> - Result with mesh URL or error
 */
export async function generateFastMesh(formData: FormData): Promise<GenerateMeshResult> {
  try {
    const falKey = getFalKey();
    if (!falKey) {
      return { success: false, error: "FAL_KEY not configured" };
    }

    console.log("[Server Action] Starting Fal.ai InstantMesh generation");

    const file = formData.get("face_photo") as File;
    if (!file) {
      return {
        success: false,
        error: "No face photo provided"
      };
    }

    // Convert to base64
    const arrayBuffer = await file.arrayBuffer();
    const base64 = Buffer.from(arrayBuffer).toString('base64');
    const mimeType = file.type || 'image/jpeg';
    const dataUrl = `data:${mimeType};base64,${base64}`;

    const payload = {
      image_url: dataUrl,
      // InstantMesh parameters for faster generation
      sample_steps: 75,
      seed: Math.floor(Math.random() * 1000000),
    };

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), FAL_FETCH_TIMEOUT_MS);

    let response: Response;
    try {
      response = await fetch(FAL_FACE_TO_3D_URL, {
        method: "POST",
        signal: controller.signal,
        headers: {
          "Authorization": `Key ${falKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });
    } finally {
      clearTimeout(timeoutId);
    }

    if (!response.ok) {
      const errorData = await response.json();
      return {
        success: false,
        error: `InstantMesh API error: ${errorData.error?.message || response.statusText}`
      };
    }

    const result = await response.json() as Fal3DResponse;
    
    if (!result.model_url) {
      return {
        success: false,
        error: "No 3D mesh generated by InstantMesh"
      };
    }

    console.log("[Server Action] InstantMesh generated successfully:", result.model_url);

    return {
      success: true,
      meshUrl: result.model_url
    };

  } catch (error) {
    console.error("[Server Action] InstantMesh generation failed:", error);
    const msg =
      error instanceof Error
        ? error.name === "AbortError"
          ? `3D request timed out after ${FAL_FETCH_TIMEOUT_MS / 1000}s`
          : error.message
        : "Unknown error occurred";
    return { success: false, error: msg };
  }
}